version: 0.2

phases:
  pre_build:
    commands:
    - echo Setting up variables
    - REPOSITORY_URI=198118428450.dkr.ecr.us-east-2.amazonaws.com/auto_pr_versioning_sandbox
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
    - echo Building the Docker image
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    - echo Pushing Docker image to ECR
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file
    - printf '[{"name":"picwell-app-staging","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
  post_build:
    commands:
    - echo Docker Build completed and image pushed on `date`
artifacts:
    files: imagedefinitions.json