version: 0.2

env:
  variables:
    GIT_REPO_NAME: "picwell/auto_pr_versioning"
  parameter-store:
    GIT_ACCESS_TOKEN: "GIT_ACCESS_TOKEN"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=198118428450.dkr.ecr.us-east-1.amazonaws.com/auto_pr_versioning_sandbox
  build:
    commands:
    - echo Pulling the latest image
      - docker pull $REPOSITORY_URI:latest
    - echo Running Auto PR Versioner!
    - docker run -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -e "GIT_REPO_NAME=$GIT_REPO_NAME" -e "GIT_ACCESS_TOKEN=$GIT_ACCESS_TOKEN" $REPOSITORY_URI:latest
